#!/usr/bin/env bash
# This script prints numbers 1-100. But prints either Fizz or Buzz  or Fizzbuzz if its a multiple of 3 or 5 or both
i=1
while [ $i -lt 101 ]
do
if ((i % 3 == 0)) && ((i % 5 == 0)); then
	echo "FizzBuzz"
elif ((i % 3 == 0)); then
	echo "Fizz"
elif ((i % 5 == 0)); then
	echo "Buzz"
else
	echo "$i"
fi
((i++))
done
