#!/usr/bin/env bash
# This script uses the while loop to print "Best School" 10 times and "Hi" after the 9th iteration
i=1
while [ "$i" -lt 11 ]
do
	if [ "$i" -eq 9 ]; then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	((i++))
done
