#!/usr/bin/env bash
# This script uses the while loop to iterate 10 times and print "Best School" except on the 4th and 8th iterations
i=0
while [ "$i" -lt 10 ]
do
        if [ "$i" -eq 3 ]; then
                echo "bad luck"
	elif [ "$i" -eq 8 ]; then
		echo "good luck"
        else
                echo "Best School"
        fi
        ((i++))
done

