#!/usr/bin/env bash
# This script uses the while loop to itearate 20 times and prints "1-20"  except on 3 exceptions where it prints other messages
i=1
while [ $i -lt 21 ]
do
	case $i in
		4)
			echo "4"
			echo "bad luck from China"
			;;
		9)
			echo "9"
			echo "bad luck from Japan"
			;;
		17)
			echo "17"
			echo "bad luck from Italy"
			;;
		*)
			echo "$i"
			;;
	esac
	((i++))
done
