#!/usr/bin/env bash
# This script prints 12 hours and print numbers 1-59 for each iteration of the hours
hour=0
while [ $hour -lt 13 ]
do
	echo "Hour: $hour"
	minute=1
	while [ $minute -lt 60 ]
	do
		echo "$minute"
		((minute++))
	done
	((hour++))
done
