#!/usr/bin/env bash
# This script lists files in the current directory, displaying only the part after the first dash
for file in *; do
    filename=$(echo "$file" | cut -d '-' -f 2-)
    echo "$filename"
done

